service: task-manager-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    TASKS_TABLE: !Ref TasksTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt TasksTable.Arn

functions:
  healthCheck:
    handler: src/handlers/healthCheck.handler
    events:
      - http:
          path: health
          method: get
          cors: true

  createTask:
    handler: src/handlers/createTask.handler
    events:
      - http:
          path: tasks
          method: post
          cors: true

  listTasks:
    handler: src/handlers/listTasks.handler
    events:
      - http:
          path: tasks
          method: get
          cors: true

  getTask:
    handler: src/handlers/getTask.handler
    events:
      - http:
          path: tasks/{id}
          method: get
          cors: true

  updateTask:
    handler: src/handlers/updateTask.handler
    events:
      - http:
          path: tasks/{id}
          method: put
          cors: true

  deleteTask:
    handler: src/handlers/deleteTask.handler
    events:
      - http:
          path: tasks/{id}
          method: delete
          cors: true

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - "@aws-sdk/*"
    target: node20
    platform: node
    concurrency: 10

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-tasks
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: taskId
            AttributeType: S
        KeySchema:
          - AttributeName: taskId
            KeyType: HASH
