service: task-manager-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    TASKS_TABLE: !Ref TasksTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt TasksTable.Arn

functions:
  - ${file(functions/healthCheck.yml)}
  - ${file(functions/createTask.yml)}
  - ${file(functions/listTasks.yml)}
  - ${file(functions/getTask.yml)}
  - ${file(functions/updateTask.yml)}
  - ${file(functions/deleteTask.yml)}

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - "@aws-sdk/*"
    target: node20
    platform: node
    concurrency: 10

resources:
  - ${file(resources/dynamodb.yml)}
